# basic
title: Daily
subtitle: Minimalism, simplicity and refined details
favicon: favicon.ico

# avatar: images/avatar.png
# banner_small: images/banner-small.png
# banner_large: images/banner-large.png
# logo: http://dummyimage.com/150x60/000/fff

# disqus
#disqus_shortname: drakeleung


# nav #
nav:
  home: .
  archive: archives
  # about: about
  # rss: atom.xml

# hexo-renderer-sass
node_sass:
  outputStyle: nested
  precision: 5
  sourceComments: false

# Default post title
default_post_title: Untitled

# social
social:
  github: https://github.com/GallenHu
  # weibo: http://weibo.com/10010800
  # mail: mailto:gallenhu@foxmail.com
  # twitter: https://twitter.com/GallenHu

# widget
#   title: 标题
#   content: 内容
widget:
  title: 关于本站
  content: <ul><li><a href="https://github.com/GallenHu/hexo-theme-Daily">如何自定义这里的内容(配置教程)?</a></li></ul>
